name: app

networks:
  my_custom_network: # Define a custom network
    driver: bridge


services:
  app:
    build: api
    image: ml
    container_name: app
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    networks:
      - my_custom_network
    volumes:
      - ./api/src:/app/src:ro

  db:
    image: postgres:17.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - my_custom_network
  
  web_server:
    image: nginx:1.27.3
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - my_custom_network
    depends_on:
      - app
