name: app

networks:
  my_custom_network: # Define a custom network
    driver: bridge


services:
  api:
    build: api
    image: api
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
    ports:
      - "8000:8000"
    networks:
      - my_custom_network
    depends_on:
      - db
      - redis
    volumes:
      - ./api/src:/app/src:ro

  db:
    image: postgres:17.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - my_custom_network
  
  web_server:
    image: web_server
    build: ./web_server
    ports:
      - "80:80"
    networks:
      - my_custom_network
    volumes:
      - ./web_server/src:/usr/share/nginx/html/:ro
    depends_on:
      - api
  
  redis:
    image: redis:8.0-M03-alpine
    container_name: redis
    ports:
      - "6379:6379"  # Порт для подключения к Redis
    networks:
      - my_custom_network
